apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-demo
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-demo
  template:
    metadata:
      labels:
        app: docker-demo
    spec:
      containers:
      - image: ravi6490/docker-demo:v1
        name: learning-kubernetes
        ports:
        - name: http
          containerPort: 8080
