apiVersion: v1
kind: Service
metadata:
  name: docker-demo
  namespace: demo
  labels:
    app: docker-demo
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 81
    protocol: TCP
    targetPort: 8080
  selector:
    app: docker-demo
